// Copyright (c) 2026 DevBench contributors. MIT License.
export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  tags: string[];
  readMinutes: number;
  relatedToolSlug?: string;
  relatedToolLabel?: string;
  relatedToolHref?: string;
  relatedBlogSlugs?: string[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "browser-code-playground-privacy",
    title: "Browser code playgrounds: what runs where (and what never leaves your tab)",
    date: "2026-05-08",
    excerpt:
      "Online playgrounds mix iframes, WebAssembly, and remote compilers. Here is a practical map of which pieces stay local, which hit a third-party API, and how to choose a flow for secrets and stdin-heavy programs.",
    tags: ["devtools", "python", "javascript", "security"],
    readMinutes: 6,
    relatedToolSlug: "code-playground",
    relatedToolLabel: "Code playground",
    relatedToolHref: "/playground",
  },
  {
    slug: "how-base64-encoding-works-and-when-not-to-use-it",
    title: "How Base64 encoding works — and when NOT to use it",
    date: "2026-05-08",
    excerpt:
      "Base64 turns binary into printable ASCII — useful for email, JSON, and data URIs. Here is how the encoding actually works, why it inflates size by ~33%, and the dangerous cases where people mistake it for encryption.",
    tags: ["encoding", "security", "web"],
    readMinutes: 9,
    relatedToolSlug: "base64-encode",
    relatedToolLabel: "Base64 Encode",
    relatedToolHref: "/tools/base64-encode",
    relatedBlogSlugs: ["jwt-decoder-without-uploading-to-server", "encodeuricomponent-vs-encodeuri", "sha256-vs-md5-hash-functions"],
  },
  {
    slug: "jwt-security-best-practices-10-things-developers-get-wrong",
    title: "JWT security best practices — 10 things developers get wrong",
    date: "2026-05-08",
    excerpt:
      "JWTs are convenient, but misuse is everywhere: treating payloads as secret, skipping audience checks, weak HMAC keys, and storing tokens where XSS can read them. Here are ten concrete mistakes and what to do instead.",
    tags: ["jwt", "security", "auth"],
    readMinutes: 10,
    relatedToolSlug: "jwt-debugger",
    relatedToolLabel: "JWT Debugger",
    relatedToolHref: "/jwt-debugger",
    relatedBlogSlugs: ["jwt-explained", "jwt-decoder-without-uploading-to-server", "how-to-generate-secure-passwords"],
  },
  {
    slug: "yaml-vs-json-key-differences-with-real-examples",
    title: "YAML vs JSON — key differences with real examples",
    date: "2026-05-08",
    excerpt:
      "JSON is strict and universal; YAML is human-friendly and dangerously powerful. Compare syntax, types, anchors, comments, and multi-document streams — with copy-paste examples you can run through a formatter.",
    tags: ["yaml", "json", "config"],
    readMinutes: 8,
    relatedToolSlug: "yaml-formatter",
    relatedToolLabel: "YAML Formatter & Validator",
    relatedToolHref: "/tools/yaml-formatter",
    relatedBlogSlugs: ["how-to-validate-json-online", "common-json-errors", "json-to-csv"],
  },
  {
    slug: "how-to-validate-json-online",
    title: "How to Validate JSON Online (Safely)",
    date: "2026-05-08",
    excerpt:
      "Validate JSON before it breaks production APIs — what “valid JSON” means, how browser-only tools differ from server uploads, and a simple workflow you can repeat every time.",
    tags: ["json", "debugging", "web"],
    readMinutes: 5,
    relatedToolSlug: "json-formatter",
    relatedToolLabel: "JSON Formatter & Validator",
    relatedToolHref: "/json",
    relatedBlogSlugs: ["common-json-errors", "yaml-vs-json-key-differences-with-real-examples", "json-to-csv"],
  },
  {
    slug: "jwt-decoder-without-uploading-to-server",
    title: "JWT Decoder Without Uploading to a Server",
    date: "2026-05-07",
    excerpt:
      "Decode JWT header and payload in the browser: why Base64 is not encryption, what stays local vs what never leaves your machine, and why decoding still isn’t verification.",
    tags: ["jwt", "security", "auth"],
    readMinutes: 5,
    relatedToolSlug: "jwt-debugger",
    relatedToolLabel: "JWT Debugger",
    relatedToolHref: "/jwt-debugger",
    relatedBlogSlugs: ["jwt-explained", "jwt-security-best-practices-10-things-developers-get-wrong", "how-base64-encoding-works-and-when-not-to-use-it"],
  },
  {
    slug: "uuid-vs-ulid-vs-nanoid",
    title: "UUID vs ULID vs Nano ID: Which Should You Use?",
    date: "2026-05-05",
    excerpt:
      "UUID v4 is everywhere, but ULID and Nano ID solve real problems UUID can't. Here's a practical breakdown of when to use each.",
    tags: ["identifiers", "databases", "javascript"],
    readMinutes: 5,
    relatedToolSlug: "uuid-generator",
    relatedToolLabel: "UUID / ULID / Nano ID Generator",
    relatedToolHref: "/tools/uuid-generator",
    relatedBlogSlugs: ["how-to-generate-secure-passwords", "sha256-vs-md5-hash-functions"],
  },
  {
    slug: "jwt-explained",
    title: "JWT Explained: Header, Payload, and Signature Decoded",
    date: "2026-05-04",
    excerpt:
      "What actually goes inside a JSON Web Token? We break down every part of a JWT, explain the signature algorithm, and show the common pitfalls.",
    tags: ["auth", "security", "jwt"],
    readMinutes: 6,
    relatedToolSlug: "jwt-debugger",
    relatedToolLabel: "JWT Debugger",
    relatedToolHref: "/jwt-debugger",
    relatedBlogSlugs: ["jwt-security-best-practices-10-things-developers-get-wrong", "jwt-decoder-without-uploading-to-server", "how-base64-encoding-works-and-when-not-to-use-it"],
  },
  {
    slug: "encodeuricomponent-vs-encodeuri",
    title: "URL Encoding: encodeURIComponent vs encodeURI Explained",
    date: "2026-05-03",
    excerpt:
      "JavaScript has two URL encoding functions and most developers mix them up. Here's exactly when to use each one — and what breaks when you don't.",
    tags: ["javascript", "web", "urls"],
    readMinutes: 4,
    relatedToolSlug: "url-encode",
    relatedToolLabel: "URL Encoder / Decoder",
    relatedToolHref: "/tools/url-encode",
    relatedBlogSlugs: ["how-base64-encoding-works-and-when-not-to-use-it", "how-to-validate-json-online"],
  },
  {
    slug: "common-json-errors",
    title: "What Makes JSON Invalid? The 7 Most Common JSON Syntax Errors",
    date: "2026-05-02",
    excerpt:
      "Trailing commas, single quotes, comments — these valid JavaScript patterns silently break JSON parsers. Learn to spot and fix all of them.",
    tags: ["json", "debugging", "javascript"],
    readMinutes: 4,
    relatedToolSlug: "json-formatter",
    relatedToolLabel: "JSON Formatter & Validator",
    relatedToolHref: "/json",
    relatedBlogSlugs: ["how-to-validate-json-online", "yaml-vs-json-key-differences-with-real-examples", "json-to-csv"],
  },
  {
    slug: "regex-cheat-sheet-javascript",
    title: "Regular Expressions Cheat Sheet for JavaScript Developers",
    date: "2026-05-01",
    excerpt:
      "The 20 regex patterns every JavaScript developer actually uses — email, URL, IP address, date, and more — with copy-ready code.",
    tags: ["regex", "javascript", "reference"],
    readMinutes: 7,
    relatedToolSlug: "regex-tester",
    relatedToolLabel: "Regex Tester",
    relatedToolHref: "/tools/regex-tester",
    relatedBlogSlugs: ["cron-expression-syntax-guide", "unix-timestamps-explained"],
  },
  {
    slug: "how-to-generate-secure-passwords",
    title: "How to Generate Secure Passwords: A Developer's Guide",
    date: "2026-05-15",
    excerpt:
      "What makes a password truly secure — entropy, character sets, length — and how to generate cryptographically strong passwords in JavaScript, Python, and on the command line.",
    tags: ["security", "javascript"],
    readMinutes: 5,
    relatedToolSlug: "password-generator",
    relatedToolLabel: "Password Generator",
    relatedToolHref: "/tools/password-generator",
    relatedBlogSlugs: ["sha256-vs-md5-hash-functions", "uuid-vs-ulid-vs-nanoid", "jwt-security-best-practices-10-things-developers-get-wrong"],
  },
  {
    slug: "sha256-vs-md5-hash-functions",
    title: "SHA-256 vs MD5: Which Hash Function Should You Use?",
    date: "2026-05-15",
    excerpt:
      "MD5 is fast and broken; SHA-256 is the modern baseline. A practical breakdown of hash functions, collision resistance, and when to reach for bcrypt or Argon2 instead.",
    tags: ["security", "devtools"],
    readMinutes: 6,
    relatedToolSlug: "hash-generator",
    relatedToolLabel: "Hash Generator",
    relatedToolHref: "/tools/hash-generator",
    relatedBlogSlugs: ["how-to-generate-secure-passwords", "how-base64-encoding-works-and-when-not-to-use-it"],
  },
  {
    slug: "cron-expression-syntax-guide",
    title: "Cron Expression Syntax: A Complete Guide with Examples",
    date: "2026-05-15",
    excerpt:
      "Master cron expression syntax from the five standard fields through extended six-field formats, special strings, and common scheduling patterns with copy-ready examples.",
    tags: ["devtools", "reference"],
    readMinutes: 7,
    relatedToolSlug: "cron-parser",
    relatedToolLabel: "Cron Expression Parser",
    relatedToolHref: "/tools/cron-parser",
    relatedBlogSlugs: ["unix-timestamps-explained", "regex-cheat-sheet-javascript"],
  },
  {
    slug: "unix-timestamps-explained",
    title: "Unix Timestamps Explained for Developers",
    date: "2026-05-15",
    excerpt:
      "Unix timestamps are the lingua franca of time in software — what they are, how to work with them in JavaScript and Python, common pitfalls around timezones and milliseconds, and the 2038 problem.",
    tags: ["devtools", "javascript"],
    readMinutes: 5,
    relatedToolSlug: "unix-timestamp",
    relatedToolLabel: "Unix Timestamp Converter",
    relatedToolHref: "/tools/unix-timestamp",
    relatedBlogSlugs: ["cron-expression-syntax-guide", "regex-cheat-sheet-javascript"],
  },
  {
    slug: "hex-rgb-hsl-css-colors-explained",
    title: "HEX, RGB, HSL: CSS Color Formats Explained",
    date: "2026-05-15",
    excerpt:
      "HEX, RGB, HSL, and modern CSS color formats each have a job: copy from design tools, manipulate programmatically, or communicate intent. Here is when to use each and how to convert between them.",
    tags: ["web", "reference"],
    readMinutes: 6,
    relatedToolSlug: "color-converter",
    relatedToolLabel: "Color Converter",
    relatedToolHref: "/tools/color-converter",
  },
  {
    slug: "celsius-to-fahrenheit-converter",
    title: "Celsius to Fahrenheit: Formula, Examples & Quick Reference Chart",
    date: "2026-05-16",
    excerpt:
      "The exact formula, a quick mental trick, and a reference table for every temperature that matters — freezing, body temp, oven settings, and more.",
    tags: ["temperature", "converter", "math", "reference"],
    readMinutes: 5,
    relatedToolSlug: "temperature-converter",
    relatedToolLabel: "Temperature Converter",
    relatedToolHref: "/tools/temperature-converter",
  },
  {
    slug: "morse-code-alphabet-chart",
    title: "Morse Code Alphabet: Complete A–Z Chart, Numbers & How to Use It",
    date: "2026-05-16",
    excerpt:
      "A complete Morse code reference: every letter, digit, and common punctuation mark, plus a brief history and where Morse is still used today.",
    tags: ["encoding", "morse-code", "reference", "communication"],
    readMinutes: 5,
    relatedToolSlug: "morse-code",
    relatedToolLabel: "Morse Code Translator",
    relatedToolHref: "/tools/morse-code",
  },
  {
    slug: "pythagorean-theorem-examples",
    title: "Pythagorean Theorem: Formula, Worked Examples & Calculator",
    date: "2026-05-16",
    excerpt:
      "a² + b² = c² explained from scratch: finding the hypotenuse, solving for a missing leg, Pythagorean triples, and real-world applications with step-by-step worked examples.",
    tags: ["math", "geometry", "calculator", "education"],
    readMinutes: 6,
    relatedToolSlug: "pythagorean-theorem",
    relatedToolLabel: "Pythagorean Theorem Calculator",
    relatedToolHref: "/tools/pythagorean-theorem",
  },
  {
    slug: "merge-pdf-online",
    title: "How to Merge PDFs Online for Free (Browser, macOS, CLI)",
    date: "2026-06-07",
    excerpt:
      "Combine multiple PDFs into one without uploading to a server. Covers browser-based tools, macOS Preview, Ghostscript, and Python pypdf — with tips on file size, fonts, and password-protected PDFs.",
    tags: ["pdf", "tools", "productivity"],
    readMinutes: 6,
    relatedToolSlug: "merge-pdf",
    relatedToolLabel: "PDF Merger",
    relatedToolHref: "/tools/merge-pdf",
    relatedBlogSlugs: ["image-to-pdf"],
  },
  {
    slug: "image-to-pdf",
    title: "How to Convert Images to PDF Online (JPG, PNG, HEIC — Free)",
    date: "2026-06-07",
    excerpt:
      "Convert photos and screenshots to PDF without uploading them anywhere. Covers JPEG, PNG, WebP, HEIC, and TIFF — with browser tools, macOS, Windows, and ImageMagick CLI methods.",
    tags: ["pdf", "image", "converter", "tools"],
    readMinutes: 5,
    relatedToolSlug: "image-to-pdf",
    relatedToolLabel: "Image to PDF Converter",
    relatedToolHref: "/tools/image-to-pdf",
    relatedBlogSlugs: ["merge-pdf-online"],
  },
  {
    slug: "loan-emi-calculator",
    title: "EMI Calculator: Formula, How to Calculate Monthly Loan Installments",
    date: "2026-06-07",
    excerpt:
      "Understand the EMI formula, see a full worked example for a ₹50 lakh home loan, compare how rate and tenure affect total interest paid, and learn how prepayment reduces your cost.",
    tags: ["finance", "calculator", "loans", "india"],
    readMinutes: 7,
    relatedToolSlug: "loan-emi-calculator",
    relatedToolLabel: "Loan EMI Calculator",
    relatedToolHref: "/tools/loan-emi-calculator",
    relatedBlogSlugs: ["bmi-calculator"],
  },
  {
    slug: "bmi-calculator",
    title: "BMI Calculator: What Is BMI and How to Calculate It",
    date: "2026-06-07",
    excerpt:
      "The BMI formula in metric and imperial, WHO classification table, adjusted cut-offs for Asian populations, worked examples, and an honest look at what BMI can and cannot tell you.",
    tags: ["health", "calculator", "reference"],
    readMinutes: 6,
    relatedToolSlug: "bmi-calculator",
    relatedToolLabel: "BMI Calculator",
    relatedToolHref: "/tools/bmi-calculator",
    relatedBlogSlugs: ["loan-emi-calculator"],
  },
  {
    slug: "json-to-csv",
    title: "JSON to CSV: How to Convert JSON Arrays to Spreadsheet Format",
    date: "2026-06-07",
    excerpt:
      "How JSON arrays map to CSV rows and columns, RFC 4180 quoting rules, JavaScript and Python code, and a detailed edge-case guide covering nested objects, null values, and large numbers.",
    tags: ["json", "csv", "data", "conversion"],
    readMinutes: 6,
    relatedToolSlug: "json-to-csv",
    relatedToolLabel: "JSON to CSV Converter",
    relatedToolHref: "/tools/json-to-csv",
    relatedBlogSlugs: ["how-to-validate-json-online", "common-json-errors", "yaml-vs-json-key-differences-with-real-examples"],
  },
  {
    slug: "json-schema-validation",
    title: "JSON Schema Validation: A Practical Guide with Examples",
    date: "2026-06-27",
    excerpt:
      "JSON Schema lets you define the shape and constraints of a JSON document — required fields, types, formats, and nested rules. A practical guide from basic type checks to AJV validation in Node.js.",
    tags: ["json", "validation", "javascript"],
    readMinutes: 7,
    relatedToolSlug: "json-formatter",
    relatedToolLabel: "JSON Formatter & Validator",
    relatedToolHref: "/json",
    relatedBlogSlugs: ["how-to-validate-json-online", "common-json-errors", "yaml-vs-json-key-differences-with-real-examples"],
  },
  {
    slug: "jsonpath-cheat-sheet",
    title: "JSONPath Cheat Sheet: Query Any JSON Document",
    date: "2026-06-27",
    excerpt:
      "JSONPath is XPath for JSON — a compact query language for extracting values from deeply nested documents. The complete syntax reference with expressions, filters, wildcards, and recursive descent operators.",
    tags: ["json", "reference", "javascript"],
    readMinutes: 6,
    relatedToolSlug: "json-formatter",
    relatedToolLabel: "JSON Formatter & Validator",
    relatedToolHref: "/json",
    relatedBlogSlugs: ["how-to-validate-json-online", "json-to-csv", "common-json-errors"],
  },
  {
    slug: "url-encoding-explained",
    title: "URL Encoding Explained: What %20, +, and Percent-Encoding Mean",
    date: "2026-06-27",
    excerpt:
      "Every URL you type is silently transformed before it hits a server. Understand percent-encoding, the difference between %20 and +, which characters are safe, and why encodeURIComponent is not the same as encodeURI.",
    tags: ["web", "encoding", "javascript"],
    readMinutes: 5,
    relatedToolSlug: "url-encode",
    relatedToolLabel: "URL Encoder / Decoder",
    relatedToolHref: "/tools/url-encode",
    relatedBlogSlugs: ["encodeuricomponent-vs-encodeuri", "how-base64-encoding-works-and-when-not-to-use-it"],
  },
  {
    slug: "aes-vs-rsa-encryption",
    title: "AES vs RSA: When to Use Symmetric vs Asymmetric Encryption",
    date: "2026-06-27",
    excerpt:
      "AES and RSA both encrypt data but in completely different ways. AES is fast and symmetric — both sides share a key. RSA is slow and asymmetric — public key encrypts, private key decrypts. Here is exactly when to use each, and why real-world systems use both.",
    tags: ["security", "encryption", "devtools"],
    readMinutes: 7,
    relatedToolSlug: "aes-encrypt-decrypt",
    relatedToolLabel: "AES-256-GCM Encryptor",
    relatedToolHref: "/tools/aes-encrypt-decrypt",
    relatedBlogSlugs: ["sha256-vs-md5-hash-functions", "how-to-generate-secure-passwords", "jwt-explained"],
  },
  {
    slug: "chmod-permissions-explained",
    title: "chmod Explained: Linux File Permissions, Octals, and rwx Notation",
    date: "2026-06-27",
    excerpt:
      "chmod 755, chmod 644, chmod 777 — what do these numbers actually mean? A complete guide to Unix file permissions: the rwx notation, octal values, common deployment patterns, and the setuid/setgid bits.",
    tags: ["linux", "devtools", "reference"],
    readMinutes: 6,
    relatedToolSlug: "chmod-calculator",
    relatedToolLabel: "chmod Calculator",
    relatedToolHref: "/tools/chmod-calculator",
    relatedBlogSlugs: ["dotenv-best-practices", "cron-expression-syntax-guide"],
  },
  {
    slug: "dotenv-best-practices",
    title: ".env Files: Best Practices for Secrets, CI/CD, and Security",
    date: "2026-06-27",
    excerpt:
      "The .env file is where secrets live — and where they leak. Best practices for structuring .env files, keeping secrets out of Git, providing .env.example for teammates, and injecting secrets safely in Docker and CI/CD pipelines.",
    tags: ["devtools", "security", "javascript"],
    readMinutes: 5,
    relatedToolSlug: "dotenv-parser",
    relatedToolLabel: ".env Parser",
    relatedToolHref: "/tools/dotenv-parser",
    relatedBlogSlugs: ["chmod-permissions-explained", "how-to-generate-secure-passwords"],
  },
  {
    slug: "semantic-versioning-explained",
    title: "Semantic Versioning (SemVer) Explained: Major, Minor, Patch",
    date: "2026-06-27",
    excerpt:
      "Every npm package uses MAJOR.MINOR.PATCH versioning — but not every developer knows when to bump each number. A practical guide to SemVer: what each component means, pre-release tags, and the ~ and ^ npm range operators.",
    tags: ["devtools", "javascript", "reference"],
    readMinutes: 5,
    relatedToolSlug: "semver-compare",
    relatedToolLabel: "SemVer Comparator",
    relatedToolHref: "/tools/semver-compare",
    relatedBlogSlugs: ["dotenv-best-practices", "cron-expression-syntax-guide"],
  },
  {
    slug: "sql-formatting-best-practices",
    title: "SQL Formatting Best Practices: Write Queries Anyone Can Read",
    date: "2026-06-27",
    excerpt:
      "Unformatted SQL is one of the leading causes of production bugs and slow code reviews. A practical SQL style guide: keyword casing, indentation, alias conventions, JOIN formatting, subqueries, and how CTEs make complex queries maintainable.",
    tags: ["databases", "devtools", "reference"],
    readMinutes: 6,
    relatedToolSlug: "sql-formatter",
    relatedToolLabel: "SQL Formatter",
    relatedToolHref: "/tools/sql-formatter",
    relatedBlogSlugs: ["json-to-csv", "how-to-validate-json-online"],
  },
  {
    slug: "markdown-cheat-sheet",
    title: "Markdown Cheat Sheet: Complete Syntax Reference with Examples",
    date: "2026-06-27",
    excerpt:
      "Every Markdown element in one place — headings, bold, italic, blockquotes, lists, inline code, fenced code blocks, links, images, tables, and GitHub Flavored Markdown extensions. Copy-paste ready.",
    tags: ["reference", "web", "devtools"],
    readMinutes: 7,
    relatedToolSlug: "markdown-preview",
    relatedToolLabel: "Markdown Preview",
    relatedToolHref: "/tools/markdown-preview",
    relatedBlogSlugs: ["regex-cheat-sheet-javascript", "sql-formatting-best-practices"],
  },
  {
    slug: "split-pdf-online",
    title: "How to Split a PDF Online for Free (No Upload Needed)",
    date: "2026-06-27",
    excerpt:
      "Extract individual pages or page ranges from a PDF without uploading to a server. Covers browser-based tools, macOS Preview, Python pypdf, and Ghostscript — with tips on removing pages, extracting a chapter, and handling password-protected files.",
    tags: ["pdf", "tools", "productivity"],
    readMinutes: 5,
    relatedToolSlug: "split-pdf",
    relatedToolLabel: "PDF Splitter",
    relatedToolHref: "/tools/split-pdf",
    relatedBlogSlugs: ["merge-pdf-online", "image-to-pdf"],
  },
  {
    slug: "timezones-dst-for-developers",
    title: "Time Zones and DST for Developers: What Actually Goes Wrong",
    date: "2026-06-27",
    excerpt:
      "Storing UTC is not enough — DST transitions, ambiguous clock times, and the difference between a UTC offset and a named time zone trip up even experienced developers. A practical guide to getting time right in JavaScript, PostgreSQL, and REST APIs.",
    tags: ["devtools", "javascript", "reference"],
    readMinutes: 7,
    relatedToolSlug: "timezone-converter",
    relatedToolLabel: "Timezone Converter",
    relatedToolHref: "/tools/timezone-converter",
    relatedBlogSlugs: ["unix-timestamps-explained", "cron-expression-syntax-guide"],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
